// ✏️ TEXTO EN ESPAÑOL. Misma estructura que en.js.
// Si falta una clave aquí, el sitio usa automáticamente el texto en inglés.
export default {
  meta: {
    title: 'Marea Alta Surf Bar · Montañita',
    description: 'Marea Alta Surf Bar, Montañita, Ecuador. Condiciones de surf y mareas en vivo, y la agenda semanal de fiestas.',
  },
  ui: { language: 'Idioma', mainNav: 'Principal' },
  nav: { surf: 'Surf', party: 'Fiesta', visit: 'Visítanos' },
  hero: {
    line1: 'Surf de día.',
    line2: 'Baile de noche.',
    tagline: '{full} en {town}. Revisa el oleaje y luego ven a vernos.',
    ctaSurf: 'Surf de hoy',
    ctaParty: 'Agenda de fiestas',
  },
  surf: {
    title: 'Reporte de surf',
    subtitle: 'Montañita en vivo. Míralo y luego ven por un trago.',
    waves: 'Olas',
    waveMeta: '{ft} ft · período {period}s · del {dir}',
    vibes: [
      'Pequeñas y suaves. Día de longboard o para aprender.',
      'Tamaño divertido. Bueno para casi todos los niveles.',
      'Sólidas. Los surfistas con experiencia lo van a disfrutar.',
      'Grandes. Conoce tus límites.',
    ],
    tideToday: 'Marea de hoy',
    rising: 'Subiendo',
    falling: 'Bajando',
    high: 'Alta',
    low: 'Baja',
    sunset: 'Atardecer',
    sunrise: 'Amanecer',
    windAir: 'Viento y aire',
    compass: ['N', 'NE', 'E', 'SE', 'S', 'SO', 'O', 'NO'],
    error: 'No se pudo cargar el reporte de surf. Revisa tu conexión e inténtalo de nuevo.',
    retry: 'Recargar reporte',
    credit: 'Datos: modelo marino Open-Meteo. Las horas de marea son aproximadas. Revisa siempre el mar tú mismo.',
  },
  party: { title: 'Agenda de fiestas', tonight: 'Esta noche' },
  days: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
  events: [
    { title: 'Noche Latina', note: 'Salsa, bachata y reggaetón toda la noche.' },
    { title: 'Noche de Solteros', note: 'Socializa con otros solteros.' },
    { title: 'Cerrado' },
    { title: 'Cerrado' },
    { title: 'Noche de Micrófono Abierto', note: 'Ven a tocar música con nosotros, trae un instrumento o canta o toca uno de los nuestros.' },
    { title: 'Música en Vivo', note: 'Música en vivo toda la noche.' },
    { title: 'Música en Vivo', note: 'El evento principal. Llega temprano para alcanzar lugar.' },
  ],
  visit: {
    title: 'Encuéntranos',
    text: '{full}, {town}. {hours}',
    hours: 'Abierto todos los días, desde la tarde hasta tarde en la noche.',
    openMap: 'Abrir mapa',
  },
  footer: '© {year} {full}. {town}.',
};
